### ISSUE TITLE
The POST route for transaction doesn't save to table and stored image cannot be found.

### ISSUE THREAD

**Issue by seikosantana** [Bintaaaa/Gampah-app-BackEnd#2]
See https://github.com/Bintaaaa/Gampah-app-BackEnd/blob/03bad4c126d46fa1f62b9398cdb364f37bc14039/app/Http/Controllers/TransactionController.php#L33-L59

New data is not inserted into table and method invocation completed without errors.

**Comment by Bintaaaa** [comment]
in my investigate your issues, you need to run "php artisan storage:link" in your terminal

**Comment by seikosantana** [comment]
I ran the command you specified, and it created a folder `storage` under `public` folder. Unfortunately, file still doesn't get stored in it. Data is not inserted to table as well.

**Comment by seikosantana** [comment]
Fixed in next commit. Please see https://github.com/Bintaaaa/Gampah-app-BackEnd/blob/fd714b3d5d605ecf50b79077cbce63ae8e09c674/app/Http/Controllers/TransactionController.php#L33-L57

Instead of relying to the `store()`, i moved the file into `uploads` folder and sets the filename as hashed time to avoid duplicate.
