### ISSUE TITLE
Error: Call to a member function move() on null in 

### ISSUE THREAD

**Issue by Bintaaaa** [Bintaaaa/Gampah-app-BackEnd#3]
![image](https://user-images.githubusercontent.com/79687063/144652201-ffc101ad-6edc-4f97-800f-a7aea032f5fd.png)

**Comment by seikosantana** [comment]
Yes, it supposed to be null since what you sent with postman has no file.
Here's how the request is expected to be.
![image](https://user-images.githubusercontent.com/35630407/144654575-9c6319b6-4882-4ef0-9984-4892b41821ab.png)

having report_img as a file. Please reopen the issue if necessary.

**Comment by Bintaaaa** [comment]
not work

![image](https://user-images.githubusercontent.com/79687063/144656075-0ec8a6d8-0fd5-4745-aee5-2a8ac04e7a85.png)

**Comment by seikosantana** [comment]
I'm unable to reproduce the issue. Will just keep the issue open for further investigation. Potentially problematic on production deployment.

**Comment by Bintaaaa** [comment]
oh sorry i just need to regist a account who roles is driver and it solved
