### ISSUE TITLE
File upload not standard path in laravel

### ISSUE THREAD

**Issue by Bintaaaa** [Bintaaaa/Gampah-app-BackEnd#5]
'move function' not efficient in saved file in laravel.
![WhatsApp Image 2021-12-06 at 10 44 53 PM](https://user-images.githubusercontent.com/79687063/144883427-9eaf433e-cfd5-4ff2-8841-0ef88848f369.jpeg)

bcs that i change 'move function' to 'storeAs function' and solved this issue
![image](https://user-images.githubusercontent.com/79687063/144883790-236aaaad-4883-465d-a73c-3a69ea22d4b9.png)

please pull my new commit

**Comment by seikosantana** [comment]
I had.
