### ISSUE TITLE
please change type of langitude and latitude to be Decimal(12,9) for get good accuration of currentPosititon

### ISSUE THREAD

**Issue by Bintaaaa** [Bintaaaa/Gampah-app-BackEnd#6]
![image](https://user-images.githubusercontent.com/79687063/144888067-4ad1efc5-d098-4f24-8f94-3f068a6062f5.png)

**Comment by seikosantana** [comment]
I have no clue on which file to change for the migrations. Would you mind to point that out @Bintaaaa ?
